### ISSUE TITLE
Adjust $print() for all HDF5 objects

### ISSUE THREAD

**Issue by hhoeflin** [hhoeflin/hdf5r#35]

**Comment by hhoeflin** [comment]
@mannau What should $print() return?

**Comment by hhoeflin** [comment]
see branch 35-adjust_print

**Comment by mannau** [comment]
Good start!
Just a few thoughts:

1. For file objects it could be helpful to see the access mode (e.g. read, write, append).
2. To me (as a user) the printed ID is not really helpful. Maybe we could simply state if the object is already opened or closed/invalid? As a compromise, maybe just state
```
Status: Open (ID: 00x93292390) or
Status: Closed
```
3. To interactively navigate through the files/groups I find it quite practical to print the underlying groups/dataset names (and maybe attributes) of the object. Just a matter of taste since `$ls()` or `list.attributes()` also does the job.
4. For datasets it would be helpful to see the dimensions, chunksize and datatype in `$print()`
5. Maybe off-topic but we should think how list.attributes could be integrated in files, groups and datasets, maybe through `$attr_list` or `$list_attr`? 

What do you think?

**Comment by hhoeflin** [comment]
Hi, 

1. Good idea on the access mode!
2. Yeah - I was already wondering about that. My backup plan here - not print an ID at all - and only print that it is invalid if it is
3. In general I like the idea, and I am not overly worried about overhead. However the printing could be difficult or hard to view if there are very many objects; so curtailing it may be an option; combining essentially an ls as well as a list.attributes
4. Planned to do all of the above for datasets
5. list.attributes now duplicates functionality of h5attr_names; but list.attributes is more efficient; could be merged; in terms of getting it into the objects, I would prefer $list_attr - feels closer to the rest of the UI where the verb comes first
6. For datatypes, will also print the raw type, i.e. double, integer, etc ...

Sound good?

**Comment by hhoeflin** [comment]
Changed printing for H5File and H5Groups, including tests as discussed.

b4dd490bb273f4975aa270e42ec303d7de617f97
d99628174fab793739dfcdd18c74761f3016db7d
ffeac8e6e39ac7d275c04a36aabae978d5b215fc

**Comment by hhoeflin** [comment]
Print methods established for 
- H5File
- H5Group
- H5D
- H5T
- H5S
- H5A
