### ISSUE TITLE
hdf5r seems to invert matricies stored in the HDF5 file

### ISSUE THREAD

**Issue by mojaveazure** [hhoeflin/hdf5r#81]
I have a 27998-row x 20000-column matrix stored in an HDF5 file. However, interacting with this file in hdf5r, it seems as though the matrix is inverted. I've connected to the same HDF5 file with hdf5r and [h5](https://github.com/mannau/h5), which I used before it was deprecated in favor of hdf5r. When loading the matrix into R, the matrix is inverted compared to how I read put it in (using h5py). Is this inversion documented somewhere that I missed? Can this be flipped to be row-by-column instead of column-by-row like other HDF5 libraries?

```R
> hfile <- hdf5r::h5file(filename = '1M_neurons_neuron20k.loom', mode = 'r')
> tfile <- h5::h5file(name = '1M_neurons_neuron20k.loom', mode = 'r')
> hfile[['matrix']]
Class: H5D
Dataset: /matrix
Filename: /home/paul/sandbox/loomR/1M_neurons_neuron20k.loom
Access type: H5F_ACC_RDONLY
Datatype: H5T_IEEE_F32LE
Space: Type=Simple     Dims=20000 x 27998     Maxdims=Inf x 27998
Chunk: 64 x 64
> hfile[['matrix']]$dims
[1] 20000 27998
> tfile@location
[1] "/home/paul/sandbox/loomR/1M_neurons_neuron20k.loom"
> tfile['matrix']@dim
[1] 27998 20000
```

**Comment by hhoeflin** [comment]
Hi,

thanks for your comments. Yes, this is known and intentional. The underlying reason is that in R in an array, the first dimension is the one changing the fastest (as is the case for Fortran). In HDF5, the fastest changing index is the last dimension of the array  (as for C arrays). In numpy in python, the fastest changing index is the last, same as in C, so you get the same ordering as in h5py as in the hdf5 file. 

So, the only alternative to reversing all dimensions (as is done here), would be to reorder the array (i.e. transpose the matrix on every read and write). hdf5r has erred on the side of efficiency and not chosen this route. If you really want to have the matrix as rows and columns as in python, you have to transpose it.

**Comment by hhoeflin** [comment]
Another CRAN package giving a lot more background on the issue:

Reticulate lets you manipulate python objects from inside R. It faces similar issues.

https://cran.r-project.org/web/packages/reticulate/vignettes/arrays.html
